antstackio/hover-design

.github/workflows/npm-publish.yml
lib/package.json

Chores/release v0.1.6

---

docs/docs/components/badge.mdx

The example in badge docs is wrong and misses some code, fixed it

Fix incorrect code snippet in docs

---

docs/docs/components/divider.mdx
lib/package.json
lib/src/components/Divider/Divider.tsx
lib/src/components/Divider/divider.css.ts
lib/src/components/Divider/divider.types.ts
lib/src/components/Divider/index.ts
lib/src/index.ts
pnpm-lock.yaml

HOV-16 | Divider component

---

docs/package.json
lib/package.json
pnpm-lock.yaml

Bumps docusaurus to version 2.0
Always better to work with a stable release of a library
Tested in dev env

bumps docusaurus to 2.0 (stable)

---

lib/src/components/Accordion/Accordion.tsx

Fix Accordion Type Issue

---

examples/vanilla-extract-react/package.json
examples/vanilla-extract-react/src/App.tsx
pnpm-lock.yaml

fix: add hover-design to package

---

docs/docs/contribution.md
docs/docs/wiki/getting_started.md
docs/docs/wiki/ideas.md
docs/docs/wiki/project_stack_reasonings.md
lib/.npmignore
lib/package.json
lib/src/components/Button/Button.stories.tsx
lib/src/components/Button/Button.tsx
lib/src/components/Button/button.types.ts
package.json
pnpm-lock.yaml
turbo.json

Adds Ladel (an alternative to storybook) read more [here](https://ladle.dev/) 
It was becoming taxing to test out the components you are making, to resolve this. I have added ladel, check out
`lib/button/button.stories.tsx` to see how to set up stories.
To run ladel, run `pnpm ladle`  in the root
Tested with button story

Adds Ladel and stories for button

---

docs/docs/components/input.mdx

Fixes issue described in #98 
#98

Fix #98: Documentation for <Input />

---

docs/docs/contribution.md

#91 
Improve user experience
In local environment 
- [  `x` ] Bug fix (non-breaking change which fixes an issue)
- [ `x` ] My code follows the code style of this project.

Fixing broken link

---

docs/docs/intro.md

will be taken up in [v0.1.9-alpha](https://github.com/antstackio/hover-design/milestone/4)

HOV-41  | Update version in intro md

---

docs/docs/components/grid.mdx
lib/src/components/Grid/Grid.tsx
lib/src/components/Grid/grid.types.ts
lib/src/components/Grid/index.ts
lib/src/index.ts

Adds Grid Component
No Grid component :(
Tested in docs

HOV-42 | Adds Grid and docs

---

docs/docs/components/list.mdx
examples/vanilla-extract-react/src/App.tsx
lib/src/components/List/List.tsx
lib/src/components/List/list.css.ts
lib/src/components/ListItem/ListItem.tsx
lib/src/components/ListItem/list-item.css.ts

Fixes to List mentioned in #104 
List having issues with the `type` prop and li items getting a wrong class assigned
tested in dev
Note to be taken in v0.1.9-alpha

HOV-39 | Fixes to list

---

lib/Readme.md
lib/package.json

HOV-46 | Adds Readme for `lib` folder and keywords

---

lib/src/components/Button/Button.tsx
lib/src/components/Button/button.styles.css.ts
lib/src/components/Button/button.types.ts
lib/src/components/Button/index.ts

Does the following fixes to button component:
- Adds forward-able ref to button
- classname is not overwritten but now is merged
- removed opnionated `fontFamily` from styles
- renamed styles file to `.styles.css.ts` format to keep up with codebase standard
To make button follow the coding standards of the projects
Tested in local
closes #52

HOV-49 | adjustments to button

---

lib/src/components/Breadcrumb/BreadCrumb.stories.tsx
lib/src/components/Breadcrumb/Breadcrumb.tsx
lib/src/components/Breadcrumb/breadcrumb.types.ts
lib/src/components/Breadcrumb/index.ts

Sanity fixes for breadcrumbs

---

lib/package.json

NOTE: MERGE LAST!!! | Bumps lib to 0.1.10 for release

---

lib/src/components/Portal/index.ts
lib/src/index.ts

Adds Portal to lib exports for consuming

Add Portal to exports

---

lib/package.json

chore:version update

---

docs/docs/components/select.mdx
docs/package.json
docs/src/components/examples/AccordionAdvancedUsage.tsx
lib/src/components/Portal/Portal.tsx
lib/src/components/Portal/index.ts
lib/src/components/Portal/portal.style.css.ts
lib/src/components/Portal/portal.types.ts
lib/src/components/Select/Select.tsx
lib/src/components/Select/select.css.ts
lib/src/components/Select/select.global.styles.css.ts
lib/src/components/Select/select.types.ts
pnpm-lock.yaml

Converted Select dropDown to portal and modified Portal component
The above change was required to fix the dropDown nesting inside modals etc
Manual Test and Build Success

Select portal

---

lib/src/components/Dialog/Dialog.tsx
lib/src/components/Modal/Modal.tsx
lib/src/components/Popover/Popover.tsx

Fixes bugs reported by sonar cloud
clean sonar cloud issues

HOV-80 | fix:sonar-cloud bugs

---

packages/lib/src/components/Accordion/accordion.types.ts
packages/lib/src/components/Alert/Alert.tsx
packages/lib/src/components/Banner/Banner.tsx
packages/lib/src/components/Breadcrumb/BreadCrumb.stories.tsx
packages/lib/src/components/Checkbox/Checkbox.stories.tsx
packages/lib/src/components/Divider/Divider.tsx
packages/lib/src/components/Divider/divider.types.ts
packages/lib/src/components/Label/label.types.ts
packages/lib/src/components/NativeSelect/NativeSelect.tsx
packages/lib/src/components/Radio/Radio.stories.tsx
packages/lib/src/components/Select/Pill/Pill.tsx
packages/lib/src/components/Tab/Tabs.tsx
packages/lib/src/components/TextArea/TextArea.tsx
packages/lib/src/hooks/useClickOutside.tsx
packages/lib/src/hooks/useTrapFocus.tsx
packages/lib/src/utils/object-utils.ts

Fixes lint issues

---

packages/lib/src/components/HoverProvider/HoverProvider.tsx
packages/lib/src/components/HoverProvider/HoverProvider.types.ts
packages/lib/src/components/HoverProvider/index.ts
packages/lib/src/index.ts

Adds a hover provider and takes a custom object to be used around the app
to make the theme object acessible externally (for now) and internally (todo)
tested on docs

HOV-88 | Adds hover provider

---

docs/docs/components/radio.mdx
packages/lib/src/components/Radio/Radio.tsx
packages/lib/src/components/Radio/RadioGroup/RadioGroup.tsx
packages/lib/src/components/Radio/radio.styles.css.ts
packages/lib/src/components/Radio/radio.types.ts
packages/lib/src/utils/access-defined-values/access-defined-values.ts
packages/lib/src/utils/index.ts

HOV-104 | Create Util function to handle custom values

---

packages/lib/src/components/Select/Pill/Pill.tsx
packages/lib/src/components/Select/Pill/pill.css.ts
packages/lib/src/components/Select/Select.tsx
packages/lib/src/components/Select/select.css.ts
packages/lib/src/components/Select/select.types.ts

Changes: 
- Converted placeholder containers to input 
- Changes in SVG types 
- exported SelectValueType
-  Changed Pill icon
- Reduced Pill Size
- increased default minHeight
- Inherited font styles
- and minor styling changes
Manual Testing and local build success

Feat: Select Enhancements

---

docs/static/robots.txt

Adding robotos.txt to static directory make it accessible in the url `hover.antstack.com/robots.txt`, since ahref tool is crawling & flagging this error on all subdomains under antstack.com
SEO Related Change
NA

Adds robots.txt file
